### ISSUE TITLE
Post Pack to Modrinth

### ISSUE THREAD

**Issue by CodeF53** [ruvaldak/AquaHUD#3]
Modrinth is adding resourcepacks!

They are fully implemented right now, their tab isn't shown yet to give resource pack devs time to upload.

https://modrinth.com/resourcepacks

Seeing how you link mainly to modrinth mods, I assume you probably want to put your pack on modrinth.

**Comment by ruvaldak** [comment]
oh amazing, thank you.

**Comment by ruvaldak** [comment]
https://modrinth.com/resourcepack/aquahud

How cool is that?
